---
version: "2"
plugins:
  fixme:
    enabled: true
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Documentation:
        enabled: false
exclude_patterns:
  - "Gemfile"
  - "ubw-client.gemspec"
  - "spec/"