---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.4
branches:
  only:
    - devel
    - wip
    - uat
    - master
install:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec